name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yaml
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        node-version:
          - 18.4.0
        os:
          - ubuntu-20.04

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: debug payload
        run: cat ${{ github.event_path }}

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate all commits from Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          pnpm commitlint \
            --from ${{ github.event.pull_request.base.sha }} \
            --to ${{ github.event.pull_request.head.sha }} \
            --verbose

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: ^7.11.0

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependency
        run: pnpm i --ignore-scripts

      - name: Lint
        run: pnpm lint
